export const Identifiers = {
	SnapshotAction: Symbol.for("Snapshot<Action>"),
	SnapshotBlockRepository: Symbol.for("Snapshot<BlockRepository>"),
	SnapshotCodec: Symbol.for("Snapshot<Codec>"),
	ProgressDispatcher: Symbol.for("Snapshot<ProgressDispatcher>"),
	SnapshotDatabaseConnection: Symbol.for("Snapshot<DatabaseConnection>"),
	SnapshotDatabaseService: Symbol.for("Service<SnapshotDatabase>"),
	SnapshotFilesystem: Symbol.for("Snapshot<Filesystem>"),
	SnapshotRepositoryFactory: Symbol.for("Factory<SnapshotRepository>"),
	StreamReaderFactory: Symbol.for("Factory<StreamReader>"),
	SnapshotRoundRepository: Symbol.for("Snapshot<RoundRepository>"),
	StreamWriterFactory: Symbol.for("Factory<StreamWriter>"),
	SnapshotTransactionRepository: Symbol.for("Snapshot<TransactionRepository>"),
	SnapshotVersion: Symbol.for("Snapshot<Version>"),
};
