version: "3.7"

services:
    postgres:
        image: postgres:16-alpine3.18@sha256:d171d14965e28764824b33974d038aea3a6be3bf0ced3c8656c848df9b7218c5
        tmpfs: /pgtmpfs
        logging:
            driver: "none"
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: test_db
            POSTGRES_PASSWORD: password
            PGDATA: /pgtmpfs
        ports:
            - "127.0.0.1:5432:5432"
