version: "3.7"

services:
    postgres:
        image: postgres:16
        tmpfs: /pgtmpfs
        logging:
            driver: "none"
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: test_db
            POSTGRES_PASSWORD: password
            PGDATA: /pgtmpfs
        ports:
            - "127.0.0.1:5432:5432"
