version: "3.7"

services:
    postgres:
        image: postgres:16
        tmpfs: /pgtmpfs
        logging:
            driver: "none"
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: test_db
            POSTGRES_PASSWORD: password
            PGDATA: /pgtmpfs
        ports:
            - "127.0.0.1:5432:5432"

    verdaccio:
        image: verdaccio/verdaccio:5
        container_name: 'verdaccio'
        tty: true
        privileged: true
        environment:
            - VERDACCIO_PORT=4873
        ports:
            - '4873:4873'
        volumes:
            - './storage:/verdaccio/storage:Z,U'
            - './config:/verdaccio/conf:Z,U'
            - './plugins:/verdaccio/plugins:Z,U'