version: "3.7"

services:
    postgres:
        image: postgres:15-alpine3.17@sha256:207a30515abe9fe51666e1821617ce83324690f3d3fc3183e23f301d35a75815
        tmpfs: /pgtmpfs
        logging:
            driver: "none"
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: test_db
            POSTGRES_PASSWORD: password
            PGDATA: /pgtmpfs
        ports:
            - "127.0.0.1:5432:5432"
