packages:
  - "packages/**"
  - "tests/**"
  - "!tests/e2e/consensus"
allowBuilds:
  bcrypto: true
  better-sqlite3: true
  bstring: true
  es5-ext: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nsfw: true
  nx: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@mainsail/evm-linux-arm64-gnu@0.0.1-evm.51'
  - '@mainsail/evm-linux-x64-gnu@0.0.1-evm.51'
