export const Identifiers = {
	ApiNodeRepositoryFactory: Symbol.for("API<Factory.ApiNodeRepository>"),
	BlockRepositoryFactory: Symbol.for("API<Factory.BlockRepository>"),
	ConfigurationRepositoryFactory: Symbol.for("API<Factory.ConfigurationRepository>"),
	ContractRepositoryFactory: Symbol.for("API<Factory.ContractRepository>"),
	DataSource: Symbol.for("API<DataSource>"),
	LegacyColdWalletRepositoryFactory: Symbol.for("API<Factory.LegacyColdWalletRepositoryFactory>"),
	Migrations: Symbol.for("API<Migrations>"),
	MultiPaymentRepositoryFactory: Symbol.for("API<Factory.MultiPaymentRepositoryFactory>"),
	PeerRepositoryFactory: Symbol.for("API<Factory.PeerRepositoryFactory>"),
	PluginRepositoryFactory: Symbol.for("API<Factory.PluginRepositoryFactory>"),
	StateRepositoryFactory: Symbol.for("API<Factory.StateRepositoryFactory>"),
	SystemRepositoryFactory: Symbol.for("API<Factory.SystemRepositoryFactory>"),
	TokenHolderRepositoryFactory: Symbol.for("API<Factory.TokenHolderRepositoryFactory>"),
	TokenRepositoryFactory: Symbol.for("API<Factory.TokenRepositoryFactory>"),
	TransactionRepositoryFactory: Symbol.for("API<Factory.TransactionRepositoryFactory>"),
	ValidatorRoundRepositoryFactory: Symbol.for("API<Factory.ValidatorRoundRepositoryFactory>"),
	WalletRepositoryFactory: Symbol.for("API<Factory.WalletRepositoryFactory>"),
};
