import { AppIdentifiers } from "./app-identifiers.js";

export const CliIdentifiers = {
	Cli: {
		Action: {
			AbortErroredProcess: Symbol.for("Cli<Action<AbortErroredProcess>>"),
			AbortMissingProcess: Symbol.for("Cli<Action<AbortMissingProcess>>"),
			AbortRunningProcess: Symbol.for("Cli<Action<AbortRunningProcess>>"),
			AbortStoppedProcess: Symbol.for("Cli<Action<AbortStoppedProcess>>"),
			AbortUnknownProcess: Symbol.for("Cli<Action<AbortUnknownProcess>>"),
			DaemonizeProcess: Symbol.for("Cli<Action<DaemonizeProcess>>"),
			Factory: Symbol.for("Cli<Action<Factory>>"),
			RestartProcess: Symbol.for("Action<RestartProcess>"),
			RestartRunningProcess: Symbol.for("Action<RestartRunningProcess>"),
			RestartRunningProcessWithPrompt: Symbol.for("Action<RestartRunningProcessWithPrompt>"),
		},
		Application: {
			Instance: AppIdentifiers.Instance,
			Name: AppIdentifiers.Name,
		},
		Commands: Symbol.for("Cli<Commands>"),
		Component: {
			AppHeader: Symbol.for("Cli<Component<AppHeader>>"),
			Ask: Symbol.for("Component<Ask>"),
			AskDate: Symbol.for("Component<AskDate>"),
			AskHidden: Symbol.for("Component<AskHidden>"),
			AskNumber: Symbol.for("Component<AskNumber>"),
			AskPassword: Symbol.for("Component<AskPassword>"),
			AutoComplete: Symbol.for("Component<AutoComplete>"),
			Box: Symbol.for("Component<Box>"),
			Clear: Symbol.for("Component<Clear>"),
			Confirm: Symbol.for("Component<Confirm>"),
			Error: Symbol.for("Component<Error>"),
			Factory: Symbol.for("Component<Factory>"),
			Fatal: Symbol.for("Component<Fatal>"),
			Info: Symbol.for("Component<Info>"),
			Listing: Symbol.for("Component<Listing>"),
			Log: Symbol.for("Component<Log>"),
			MultiSelect: Symbol.for("Component<MultiSelect>"),
			NewLine: Symbol.for("Component<NewLine>"),
			Prompt: Symbol.for("Component<Prompt>"),
			Select: Symbol.for("Component<Select>"),
			Spinner: Symbol.for("Component<Spinner>"),
			Success: Symbol.for("Component<Success>"),
			Table: Symbol.for("Component<Table>"),
			TaskList: Symbol.for("Component<TaskList>"),
			Title: Symbol.for("Component<Title>"),
			Toggle: Symbol.for("Component<Toggle>"),
			Warning: Symbol.for("Component<Warning>"),
		},
		Input: {
			Factory: Symbol.for("Factory<Input>"),
			Instance: Symbol.for("Input<Instance>"),
			Validator: Symbol.for("Input<Validator>"),
		},
		Output: {
			Instance: Symbol.for("Output<Instance>"),
		},
		Package: Symbol.for("Package"),
		Paths: {
			Application: Symbol.for("Paths<Application>"),
			Console: Symbol.for("Paths<Console>"),
		},
		ProcessFactory: Symbol.for("Factory<Process>"),
		Service: {
			Config: Symbol.for("Config"),
			Environment: Symbol.for("Environment"),
			Installer: Symbol.for("Installer"),
			Logger: Symbol.for("Logger"),
			PluginManager: Symbol.for("PluginManager"),
			ProcessManager: Symbol.for("ProcessManager"),
			Setup: Symbol.for("Setup"),
			Updater: Symbol.for("Updater"),
		},
	},
} as const;
