/* eslint-disable sort-keys-fix/sort-keys-fix */
export const CliIdentifiers = {
	Cli: {
		AppHeader: Symbol.for("Cli<Component<AppHeader>>"),
		// Application: {
		// 	Instance: ID.Application.Instance,
		// 	Name: ID.Application.Name,
		// },
		ApplicationPaths: Symbol.for("Paths<Application>"),
		Commands: Symbol.for("Commands"),
		Config: Symbol.for("Config"),
		ConsolePaths: Symbol.for("Paths<Console>"),
		Environment: Symbol.for("Environment"),
		Input: Symbol.for("Input"),
		InputFactory: Symbol.for("Factory<Input>"),
		InputValidator: Symbol.for("Input<Validator>"),
		Installer: Symbol.for("Installer"),
		Logger: Symbol.for("Logger"),
		Output: Symbol.for("Output"),
		Package: Symbol.for("Package"),
		PluginManager: Symbol.for("PluginManager"),
		ProcessFactory: Symbol.for("Factory<Process>"),
		ProcessManager: Symbol.for("ProcessManager"),
		Setup: Symbol.for("Setup"),
		Updater: Symbol.for("Updater"),
		Action: {
			AbortErroredProcess: Symbol.for("Cli<Action<AbortErroredProcess>>"),
			AbortMissingProcess: Symbol.for("Cli<Action<AbortMissingProcess>>"),
			AbortRunningProcess: Symbol.for("Cli<Action<AbortRunningProcess>>"),
			AbortStoppedProcess: Symbol.for("Cli<Action<AbortStoppedProcess>>"),
			AbortUnknownProcess: Symbol.for("Cli<Action<AbortUnknownProcess>>"),
			DaemonizeProcess: Symbol.for("Cli<Action<DaemonizeProcess>>"),
			Factory: Symbol.for("Cli<Action<Factory>>"),
			RestartProcess: Symbol.for("Action<RestartProcess>"),
			RestartRunningProcess: Symbol.for("Action<RestartRunningProcess>"),
			RestartRunningProcessWithPrompt: Symbol.for("Action<RestartRunningProcessWithPrompt>"),
		},
		Component: {
			Ask: Symbol.for("Component<Ask>"),
			AskDate: Symbol.for("Component<AskDate>"),
			AskHidden: Symbol.for("Component<AskHidden>"),
			AskNumber: Symbol.for("Component<AskNumber>"),
			AskPassword: Symbol.for("Component<AskPassword>"),
			AutoComplete: Symbol.for("Component<AutoComplete>"),
			Box: Symbol.for("Component<Box>"),
			Clear: Symbol.for("Component<Clear>"),
			Confirm: Symbol.for("Component<Confirm>"),
			Error: Symbol.for("Component<Error>"),
			Fatal: Symbol.for("Component<Fatal>"),
			Info: Symbol.for("Component<Info>"),
			Listing: Symbol.for("Component<Listing>"),
			Log: Symbol.for("Component<Log>"),
			MultiSelect: Symbol.for("Component<MultiSelect>"),
			Factory: Symbol.for("Component<Factory>"),
			NewLine: Symbol.for("Component<NewLine>"),
			Prompt: Symbol.for("Component<Prompt>"),
			Select: Symbol.for("Component<Select>"),
			Spinner: Symbol.for("Component<Spinner>"),
			Success: Symbol.for("Component<Success>"),
			Table: Symbol.for("Component<Table>"),
			TaskList: Symbol.for("Component<TaskList>"),
			Title: Symbol.for("Component<Title>"),
			Toggle: Symbol.for("Component<Toggle>"),
			Warning: Symbol.for("Component<Warning>"),
		},
	},
} as const;
