version: '3.5'
services:
  core:
    image: arkecosystem/mainsail-core 
    container_name: mainsail-mainnet
    restart: always
    ports:
     - "4001:4001"
     - "127.0.0.1:4004:4004"
     - "127.0.0.1:4006:4006"
     - "4007:4007"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
     - ~/.config/mainsail:/home/node/.config/mainsail
     - ~/.local/share/mainsail:/home/node/.local/share/mainsail
     - ~/.local/state/mainsail:/home/node/.local/state/mainsail
     - /etc/localtime:/etc/localtime:ro
     - ./enc:/run/secrets
    networks:
      - core
    env_file: ./mainnet.env
    tty: true
volumes:
  core:
networks:
  core:
