export const Identifiers = {
	ApiSync: {
		Listener: Symbol("ApiSync<Listener>"),
		Service: Symbol("ApiSync<Service>"),
	},
	Application: {
		DirPrefix: Symbol("Application<DirPrefix>"),
		Environment: Symbol("Application<Environment>"),
		Instance: Symbol("Application<Instance>"),
		Name: Symbol("Application<Name>"),
		Namespace: Symbol("Application<Namespace>"),
		Network: Symbol("Application<Network>"),
		Token: Symbol("Application<Token>"),
		Version: Symbol("Application<Version>"),
	},
	BlockProcessor: Symbol("Block<Processor>"),
	BlockVerifier: Symbol("Block<Verifier>"),
	Consensus: {
		Aggregator: Symbol("Aggregator<Consensus>"),
		Bootstrapper: Symbol("Bootstrapper<Consensus>"),
		CommitLock: Symbol("CommitLock<Consensus>"),
		CommitProcessor: Symbol("Consensus<Commit.Processor>"),
		CommitStateFactory: Symbol("Consensus<CommitState.Factory>"),
		PrecommitProcessor: Symbol("Consensus<Precommit.Processor>"),
		PrevoteProcessor: Symbol("Consensus<Prevote.Processor>"),
		ProposalProcessor: Symbol("Consensus<Proposal.Processor>"),
		RoundStateRepository: Symbol("Repository<Consensus.RoundState>"),
		Scheduler: Symbol("Scheduler<Consensus>"),
		Service: Symbol("Service<Consensus>"),
		Storage: Symbol("Storage<Consensus>"),
		ValidatorRepository: Symbol("Repository<Consensus.Validator>"),
	},

	Crypto: Symbol("Crypto<NetworkConfig>"),
	CryptoWorker: {
		Worker: Symbol("Ipc<Worker>"),
		WorkerFactory: Symbol("Ipc<WorkerFactory>"),
		WorkerPool: Symbol("Ipc<WorkerPool>"),
		WorkerSubprocessFactory: Symbol("Ipc<WorkerSubprocessFactory>"),
	},
	Cryptography: {
		Block: {
			Deserializer: Symbol("Crypto<Block.Deserializer>"),
			Factory: Symbol("Crypto<Block.Factory>"),
			IDFactory: Symbol("Crypto<Block.IDFactory>"),
			Serializer: Symbol("Crypto<Block.Serializer>"),
			Verifier: Symbol("Crypto<Block.Verifier>"),
		},
		Commit: {
			Deserializer: Symbol("Crypto<Commit.Deserializer>"),
			Factory: Symbol("Crypto<Commit.Factory>"),
			Serializer: Symbol("Crypto<Commit.Serializer>"),
		},
		Configuration: Symbol("Crypto<Configuration>"),
		HashFactory: Symbol("Crypto<HashFactory>"),
		Identity: {
			AddressFactory: Symbol("Crypto<Identity.AddressFactory>"),
			AddressSerializer: Symbol("Crypto<Identity.AddressSerializer>"),
			KeyPairFactory: Symbol("Crypto<Identity.KeyPairFactory>"),
			PrivateKeyFactory: Symbol("Crypto<Identity.PrivateKeyFactory>"),
			PublicKeyFactory: Symbol("Crypto<Identity.PublicKeyFactory>"),
			PublicKeySerializer: Symbol("Crypto<Identity.PublicKeySerializer>"),
			WifFactory: Symbol("Crypto<Identity.WifFactory>"),
		},
		Message: {
			Deserializer: Symbol("Crypto<Message.Deserializer>"),
			Factory: Symbol("Crypto<Message.Factory>"),
			Serializer: Symbol("Crypto<Message.Serializer>"),
		},
		Serializer: Symbol("Crypto<Serializer>"),
		Signature: Symbol("Crypto<Signature>"),
		Size: {
			Address: Symbol("Crypto<Size.Address>"),
			HASH256: Symbol("Crypto<Size.HASH256>"),
			PublicKey: Symbol("Crypto<Size.PublicKey>"),
			RIPEMD160: Symbol("Crypto<Size.RIPEMD160>"),
			SHA256: Symbol("Crypto<Size.SHA256>"),
			Signature: Symbol("Crypto<Size.Signature>"),
		},
		Transaction: {
			Deserializer: Symbol("Crypto<Transaction.Deserializer>"),
			Factory: Symbol("Crypto<Transaction.Factory>"),
			Registry: Symbol("Crypto<Transaction.Registry>"),
			Serializer: Symbol("Crypto<Transaction.Serializer>"),
			Signer: Symbol("Crypto<Transaction.Signer>"),
			TypeFactory: Symbol("Crypto<Transaction.TypeFactory>"),
			Utils: Symbol("Crypto<Transaction.Utils>"),
			Verifier: Symbol("Crypto<Transaction.Verifier>"),
		},
		Validator: Symbol("Crypto<Validator>"),
	},
	Database: {
		Instance: {
			Consensus: Symbol("Database<Instance.Consensus>"),
			Root: Symbol("Database<Instance.Root>"),
		},
		Service: Symbol("Database<Service>"),
		Storage: {
			Block: Symbol("Database<Storage.Block>"),
			ConsensusState: Symbol("Database<Storage.ConsensusState>"),
			Precommit: Symbol("Database<Storage.Precommit>"),
			Prevote: Symbol("Database<Storage.Prevote>"),
			Proposal: Symbol("Database<Storage.Proposal>"),
		},
	},

	Fee: {
		Matcher: Symbol("Fee<Matcher>"),
		Registry: Symbol("Fee<Registry>"),
		Type: Symbol("Fee<Type>"),
	},
	Kernel: {
		Cache: {
			Factory: Symbol("Kernel<Cache.Factory>"),
			Manager: Symbol("Kernel<Cache.Manager>"),
		},
		Config: {
			Flags: Symbol("Kernel<Config.Flags>"),
			Manager: Symbol("Kernel<Config.Manager>"),
			Plugins: Symbol("Kernel<Config.Plugins>"),
			Repository: Symbol("Kernel<Config.Repository>"),
		},
		EventDispatcher: {
			Manager: Symbol("Kernel<EventDispatcher.Manager>"),
			Service: Symbol("Kernel<EventDispatcher.Service>"),
		},
		Filesystem: {
			Manager: Symbol("Kernel<Filesystem.Manager>"),
			Service: Symbol("Kernel<Filesystem.Service>"),
		},
		Log: {
			Manager: Symbol("Kernel<Log.Manager>"),
			Service: Symbol("Kernel<Log.Service>"),
		},
		Mixin: {
			Service: Symbol("Kernel<Mixin.Service>"),
		},
		Pipeline: {
			Factory: Symbol("Kernel<Pipeline.Factory>"),
		},
		ProcessActions: {
			Manager: Symbol("Kernel<ProcessActions.Manager>"),
			Service: Symbol("Kernel<ProcessActions.Service>"),
		},
		Queue: {
			Factory: Symbol("Kernel<Queue.Factory>"),
			Manager: Symbol("Kernel<Queue.Manager>"),
		},
		Schedule: {
			Service: Symbol("Kernel<Schedule.Service>"),
		},
		Trigger: {
			Service: Symbol("Kernel<Trigger.Service>"),
		},
		Validation: {
			Manager: Symbol("Kernel<Validation.Manager>"),
			Service: Symbol("Kernel<Validation.Service>"),
		},
	},
	P2P: {
		Server: Symbol("P2P<Server>"),
		Service: Symbol("P2P<Service>"),
	},
	P2PLogger: Symbol("Logger<P2P>"),
	P2PServer: Symbol("Server<P2P>"),
	P2PState: Symbol("State<P2P>"),
	PeerApiNodeDiscoverer: Symbol("Peer<Discoverer.ApiNodes>"),
	PeerApiNodeFactory: Symbol("Peer<Factory.ApiNodes>"),
	PeerApiNodeProcessor: Symbol("Peer<Processor.ApiNodes>"),
	PeerApiNodeRepository: Symbol("Peer<Repository.ApiNodes>"),
	PeerApiNodeVerifier: Symbol("Peer<Verifier.ApiNodes>"),
	PeerBlockDownloader: Symbol("Peer<BlockDownloader>"),
	PeerBroadcaster: Symbol("Peer<Broadcaster>"),
	PeerCommunicator: Symbol("Peer<Communicator>"),
	PeerConnector: Symbol("Peer<Connector>"),
	PeerDiscoverer: Symbol("Peer<Discoverer>"),
	PeerDisposer: Symbol("Peer<Disposer>"),
	PeerFactory: Symbol("Factory<Peer>"),
	PeerHeaderFactory: Symbol("Factory<PeerHeader>"),
	PeerHeaderService: Symbol("Peer<HeaderService>"),
	PeerMessageDownloader: Symbol("Peer<Downloader>"),
	PeerProcessor: Symbol("Peer<Processor>"),
	PeerProposalDownloader: Symbol("Peer<ProposalDownloader>"),
	PeerRepository: Symbol("Peer<Repository>"),
	PeerThrottleFactory: Symbol("Peer<Throttle.Factory>"),
	PeerVerifier: Symbol("Peer<Verifier>"),

	PluginConfiguration: Symbol("PluginConfiguration"),
	Proposer: {
		Selector: Symbol("Proposer<Selector>"),
	},
	ServiceProviderRepository: Symbol("Repository<ServiceProvider>"),
	State: {
		AttributeRepository: Symbol("State<AttributeRepository>"),
		Exporter: Symbol("State<Exporter>"),
		Importer: Symbol("State<Importer>"),
		Service: Symbol("State<Service>"),
		Store: {
			Factory: Symbol("State<Store<Factory>>"),
		},
		ValidatorMutator: Symbol("State<ValidatorMutator>"),
		ValidatorWallet: {
			Factory: Symbol("State<ValidatorWallet<Factory>>"),
		},
		Verifier: Symbol("State<Verifier>"),
		Wallet: {
			Attributes: Symbol("State<Wallet<Attributes>>"),
			Factory: Symbol("State<Wallet<Factory>>"),
		},
		WalletRepository: {
			Base: {
				Factory: Symbol("State<WalletRepository<Base<Factory>>>"),
			},
			BySender: {
				Factory: Symbol("State<WalletRepository<BySender<Factory>>>"),
			},
			Clone: {
				Factory: Symbol("State<WalletRepository<Clone<Factory>>>"),
			},
			IndexSet: Symbol("State<WalletRepository<IndexSet>>"),
		},
	},
	TransactionHandler: Symbol("TransactionHandler"),
	TransactionHandlerConstructors: Symbol("TransactionHandlerConstructors"),
	TransactionHandlerProvider: Symbol("Provider<TransactionHandler>"),
	TransactionHandlerRegistry: Symbol("Registry<TransactionHandler>"),
	TransactionHistoryService: Symbol("Service<TransactionHistory>"),
	TransactionPool: {
		Collator: Symbol("TransactionPool<Collator>"),
		ExpirationService: Symbol("TransactionPool<ExpirationService>"),
		Mempool: Symbol("TransactionPool<Mempool>"),
		Processor: Symbol("TransactionPool<Processor>"),
		ProcessorExtension: Symbol("TransactionPool<ProcessorExtension>"),
		ProcessorFactory: Symbol("TransactionPool<ProcessorFactory>"),
		Query: Symbol("TransactionPool<Query>"),
		SenderMempoolFactory: Symbol("TransactionPool<SenderMempoolFactory>"),
		SenderState: Symbol("TransactionPool<SenderState>"),
		Service: Symbol("TransactionPool<Service>"),
		Storage: Symbol("TransactionPool<Storage>"),
	},
	TransactionProcessor: Symbol("Transaction<Processor>"),
	TransactionValidator: Symbol("State<TransactionValidator>"),
	TransactionValidatorFactory: Symbol("State<TransactionValidatorFactory>"),
	ValidatorSet: Symbol("Set<ValidatorSet>"),
};
