type EnvironmentVariable = (typeof EnvironmentVariableNames)[number];

export const EnvironmentVariableNames = [
	// Log
	"MAINSAIL_LOG_LEVEL_FILE",
	"MAINSAIL_LOG_LEVEL",

	// Pool
	"MAINSAIL_MAX_TRANSACTIONS_IN_POOL",
	"MAINSAIL_TRANSACTION_POOL_REBROADCAST_THRESHOLD",
	"MAINSAIL_TRANSACTION_POOL_DISABLED",
	"MAINSAIL_TRANSACTION_POOL_MAX_PER_REQUEST",
	"MAINSAIL_TRANSACTION_POOL_MAX_PER_SENDER",
	"MAINSAIL_TRANSACTION_POOL_MAX_PEER_BROADCAST",
	"MAINSAIL_TRANSACTION_POOL_MAX_PEER_SEQUENTIAL_ERRORS",
	"MAINSAIL_RESET_DATABASE",
	"MAINSAIL_RESET_POOL",

	// P2P
	"MAINSAIL_P2P_API_NODES_MAX_CONTENT_LENGTH",
	"MAINSAIL_P2P_API_NODES",
	"MAINSAIL_P2P_DEVELOPMENT_MODE_ENABLED",
	"MAINSAIL_P2P_HOST",
	"MAINSAIL_P2P_MAX_PEERS_BROADCAST",
	"MAINSAIL_P2P_MAX_PEERS_SAME_SUBNET",
	"MAINSAIL_P2P_MIN_NETWORK_REACH",
	"MAINSAIL_P2P_PEER_BAN_TIME",
	"MAINSAIL_P2P_PEER_LOG_EXTRA",
	"MAINSAIL_P2P_PORT",
	"MAINSAIL_P2P_RATE_LIMIT",
	"MAINSAIL_SKIP_PEER_STATE_VERIFICATION",

	// Webhooks
	"MAINSAIL_WEBHOOKS_ENABLED",
	"MAINSAIL_WEBHOOKS_HOST",
	"MAINSAIL_WEBHOOKS_PORT",
	"MAINSAIL_WEBHOOKS_TIMEOUT",
	"MAINSAIL_WEBHOOKS_WHITELIST",

	// Cli
	"MAINSAIL_NPM_REGISTRY",

	// Worker
	"MAINSAIL_CRYPTO_WORKER_COUNT",
	"MAINSAIL_CRYPTO_WORKER_LOGGING_ENABLED",

	// Database
	"MAINSAIL_DB_HOST",
	"MAINSAIL_DB_PORT",
	"MAINSAIL_DB_DATABASE",
	"MAINSAIL_DB_USERNAME",
	"MAINSAIL_DB_PASSWORD",
	"MAINSAIL_DB_LOGGING_ENABLED",

	// API
	"MAINSAIL_API_NO_ESTIMATED_TOTAL_COUNT",
	"MAINSAIL_API_CACHE",
	"MAINSAIL_API_LOG",
	"MAINSAIL_API_RATE_LIMIT_BLACKLIST",
	"MAINSAIL_API_RATE_LIMIT_USER_EXPIRES",
	"MAINSAIL_API_RATE_LIMIT_DISABLED",
	"MAINSAIL_API_RATE_LIMIT_USER_LIMIT",
	"MAINSAIL_API_RATE_LIMIT_WHITELIST",
	"MAINSAIL_API_TRUST_PROXY",
	"MAINSAIL_API_DISABLED",
	"MAINSAIL_API_HOST",
	"MAINSAIL_API_PORT",
	"MAINSAIL_API_SSL",
	"MAINSAIL_API_SSL_HOST",
	"MAINSAIL_API_SSL_PORT",
	"MAINSAIL_API_SSL_CERT",
	"MAINSAIL_API_SSL_KEY",

	"MAINSAIL_API_SYNC_ENABLED",
	"MAINSAIL_API_SYNC_INTERVAL",

	// Transaction pool API
	"MAINSAIL_API_TRANSACTION_POOL_TRUST_PROXY",
	"MAINSAIL_API_TRANSACTION_POOL_DISABLED",
	"MAINSAIL_API_TRANSACTION_POOL_HOST",
	"MAINSAIL_API_TRANSACTION_POOL_PORT",
	"MAINSAIL_API_TRANSACTION_POOL_SSL",
	"MAINSAIL_API_TRANSACTION_POOL_SSL_HOST",
	"MAINSAIL_API_TRANSACTION_POOL_SSL_PORT",
	"MAINSAIL_API_TRANSACTION_POOL_SSL_CERT",
	"MAINSAIL_API_TRANSACTION_POOL_SSL_KEY",

	// Dev API
	"MAINSAIL_API_DEV_RATE_LIMIT_BLACKLIST",
	"MAINSAIL_API_DEV_RATE_LIMIT_USER_EXPIRES",
	"MAINSAIL_API_DEV_RATE_LIMIT_DISABLED",
	"MAINSAIL_API_DEV_RATE_LIMIT_USER_LIMIT",
	"MAINSAIL_API_DEV_RATE_LIMIT_WHITELIST",
	"MAINSAIL_API_DEV_TRUST_PROXY",
	"MAINSAIL_API_DEV_ENABLED",
	"MAINSAIL_API_DEV_HOST",
	"MAINSAIL_API_DEV_PORT",
	"MAINSAIL_API_DEV_SSL",
	"MAINSAIL_API_DEV_SSL_HOST",
	"MAINSAIL_API_DEV_SSL_PORT",
	"MAINSAIL_API_DEV_SSL_CERT",
	"MAINSAIL_API_DEV_SSL_KEY",

	// EVM API
	"MAINSAIL_API_EVM_DISABLED",
	"MAINSAIL_API_EVM_HOST",
	"MAINSAIL_API_EVM_PORT",
	"MAINSAIL_API_EVM_RATE_LIMIT_BLACKLIST",
	"MAINSAIL_API_EVM_RATE_LIMIT_DISABLED",
	"MAINSAIL_API_EVM_RATE_LIMIT_USER_EXPIRES",
	"MAINSAIL_API_EVM_RATE_LIMIT_USER_LIMIT",
	"MAINSAIL_API_EVM_RATE_LIMIT_WHITELIST",
	"MAINSAIL_API_EVM_SSL_CERT",
	"MAINSAIL_API_EVM_SSL_HOST",
	"MAINSAIL_API_EVM_SSL_KEY",
	"MAINSAIL_API_EVM_SSL_PORT",
	"MAINSAIL_API_EVM_SSL",
	"MAINSAIL_API_EVM_TRUST_PROXY",

	// SNAPSHOT
	"MAINSAIL_SNAPSHOT_MOCK_FAKE_VALIDATOR_BLS_KEYS",

	// Other
	"MAINSAIL_NETWORK_NAME",
	"MAINSAIL_TOKEN",
	"MAINSAIL_VERSION",
	"MAINSAIL_ENV",
	"MAINSAIL_PATH_DATA",
	"MAINSAIL_PATH_CONFIG",
	"MAINSAIL_PATH_CACHE",
	"MAINSAIL_PATH_LOG",
	"MAINSAIL_PATH_TEMP",
] as const;

// TODO: DisconnectInvalidPeers

export const EnvironmentVariables = EnvironmentVariableNames.reduce((item, flagName) => {
	item[flagName] = flagName;
	return item;
}, {}) as Record<EnvironmentVariable, string>;
