name: CI

on:
    workflow_call:
        secrets:
            CODECOV_TOKEN:
                required: true

permissions:
    contents: read

env:
    FOUNDRY_PROFILE: ci
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
    check:
        name: contracts
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: contracts
        steps:
            - uses: actions/checkout@v7.0.1

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1.9.1
              with:
                  version: stable

            - name: Build
              run: |
                  forge build

            - name: Run test with coverage
              run: |
                  forge coverage --report lcov

            - name: Upload coverage reports to Codecov
              if: ${{ env.CODECOV_TOKEN != '' }}
              uses: codecov/codecov-action@v7.0.0
              with:
                  working-directory: contracts
                  files: ./lcov.info
                  token: ${{ env.CODECOV_TOKEN }}
                  slug: ArkEcosystem/mainsail
                  flags: contracts
