name: Dependencies

on:
    workflow_call:

permissions:
    contents: read

jobs:
    source:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6.0.2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v6.3.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v4.3.0
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache@v5.0.3
              with:
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  restore-keys: ${{ runner.os }}-pnpm-
            - name: Cache lerna
              uses: actions/cache@v5.0.3
              with:
                  key: ${{ runner.os }}-lerna
                  path: ./.cache
                  restore-keys: ${{ runner.os }}-lerna-
            - name: Install dependencies
              run: pnpm install
            - name: Check dependencies
              run: pnpm run deps:check
        strategy:
            matrix:
                node-version: [26.x]
