name: Test

on:
    workflow_call:
        secrets:
            CODECOV_TOKEN:
                required: true

permissions:
    contents: read

env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
    build:
        name: "Build"
        strategy:
            matrix:
                node-version: [24.x]
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-unit
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest

            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache pnpm modules
              uses: actions/cache@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}

            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: llvm-tools-preview

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run build

            - name: Cache lerna
              uses: actions/cache/save@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx

    unit:
        name: "Unit"
        if: true
        needs:
            - build
        strategy:
            matrix:
                node-version: [24.x]
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-unit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: llvm-tools-preview
            - name: Install cargo-llvm-cov
              run: cargo install cargo-llvm-cov
            - name: Check rustc version
              run: rustc --version
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            # The evm package is excluded here and run separately below: its coverage
            # script temporarily swaps the native addon for an instrumented build,
            # which would race against other suites loading the addon in parallel.
            - name: Test packages
              run: pnpm exec lerna run test:coverage --concurrency=4 --ignore=@mainsail/evm --ignore='@mainsail/functional-*' --ignore='@mainsail/e2e-*'

            - name: Test evm
              run: cd packages/evm && pnpm run test:coverage

            - name: Merge test coverage reports
              run: pnpm run test:unit:merge

            - name: Upload coverage reports to Codecov
              if: ${{ env.CODECOV_TOKEN != '' }}
              uses: codecov/codecov-action@v7.0.0
              with:
                  files: ./merged-lcov.info
                  token: ${{ env.CODECOV_TOKEN }}
                  slug: ArkEcosystem/mainsail
                  flags: packages

    integration:
        name: "Integration"
        if: true
        needs:
            - build
        strategy:
            matrix:
                node-version: [24.x]
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-integration
        runs-on: ubuntu-latest

        timeout-minutes: 15

        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: test_db
                    POSTGRES_PASSWORD: password
                ports:
                    - 127.0.0.1:5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Test api-http
              run: cd packages/api-http && pnpm run test:integration

    e2e-consensus:
        name: "E2E Consensus"
        if: true
        needs:
            - build
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-e2e-${{ matrix.name }}
        runs-on: ubuntu-latest

        timeout-minutes: 15

        strategy:
            matrix:
                node-version: [24.x]
                name: ["consensus"]

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Docker ${{ matrix.name }}
              run: sudo chmod -R 777 tests/e2e/${{ matrix.name }}/nodes && cd tests/e2e/${{ matrix.name }} && docker compose up -d

            - name: Running checks for ${{ matrix.name }}
              run: |
                  container_id=$(docker ps -a | grep 'consensus-checks' | awk '{print $1}')
                  while docker ps | grep -q $container_id; do echo "checks running..."; sleep 5; done
                  exit_code=$(docker container inspect $container_id --format='{{.State.ExitCode}}')
                  if [ "$exit_code" != "0" ]; then
                    echo "Error: checks exited with code $exit_code"
                    exit 1
                  fi
            - name: Show logs - checks
              if: always()
              run: docker logs consensus-checks-1
            - name: Show logs - node0
              if: always()
              run: docker logs consensus-node0-1
            - name: Show logs - node1
              if: always()
              run: docker logs consensus-node1-1
            - name: Show logs - node2
              if: always()
              run: docker logs consensus-node2-1
            - name: Show logs - node3
              if: always()
              run: docker logs consensus-node3-1
            - name: Show logs - node4
              if: always()
              run: docker logs consensus-node4-1
            - name: Show logs - api-node
              if: always()
              run: docker logs consensus-api-node-1
            - name: Show logs - api-http
              if: always()
              run: docker logs consensus-api-http-1

    e2e-clients:
        name: "E2E Clients"
        if: true
        needs:
            - build
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-e2e-${{ matrix.name }}
        runs-on: ubuntu-latest

        timeout-minutes: 10

        strategy:
            matrix:
                node-version: [24.x]
                name: ["clients"]

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Docker Up
              run: cd tests/e2e/clients && docker compose up -d
            - name: Delay
              run: sleep 20
            - name: Running checks for ${{ matrix.name }}
              run: cd tests/e2e/clients && pnpm run test
            - name: Show logs
              if: always()
              run: docker logs mainsail

    e2e-snapshot:
        name: "E2E Snapshot"
        if: true
        needs:
            - build
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-e2e-${{ matrix.name }}
        runs-on: ubuntu-latest

        timeout-minutes: 15

        strategy:
            matrix:
                node-version: [24.x]
                name: ["snapshot"]

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Docker ${{ matrix.name }}
              run: sudo chmod -R 777 tests/e2e/${{ matrix.name }}/nodes && cd tests/e2e/${{ matrix.name }} && docker compose up -d

            - name: Running checks for ${{ matrix.name }}
              run: |
                  container_id=$(docker ps -a | grep 'snapshot-checks' | awk '{print $1}')
                  while docker ps | grep -q $container_id; do echo "checks running..."; sleep 5; done
                  exit_code=$(docker container inspect $container_id --format='{{.State.ExitCode}}')
                  if [ "$exit_code" != "0" ]; then
                    echo "Error: checks exited with code $exit_code"
                    exit 1
                  fi
            - name: Show logs - node0
              if: always()
              run: docker logs snapshot-node0-1
            - name: Show logs - node1
              if: always()
              run: docker logs snapshot-node1-1
            - name: Show logs - node2
              if: always()
              run: docker logs snapshot-node2-1
            - name: Show logs - node3
              if: always()
              run: docker logs snapshot-node3-1
            - name: Show logs - node4
              if: always()
              run: docker logs snapshot-node4-1
            - name: Show logs - checks
              if: always()
              run: docker logs snapshot-checks-1

    e2e-sync:
        name: "E2E Sync"
        if: false
        needs:
            - build
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-e2e-${{ matrix.name }}
        runs-on: ubuntu-latest

        timeout-minutes: 15

        strategy:
            matrix:
                node-version: [24.x]
                name: ["sync"]

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Docker ${{ matrix.name }}
              env:
                  MINIMUM_BLOCKS_TO_SYNC: 5000
              run: sudo chmod -R 777 tests/e2e/${{ matrix.name }}/nodes && cd tests/e2e/${{ matrix.name }} && docker compose up -d

            - name: Running checks for ${{ matrix.name }}
              run: |
                  container_id=$(docker ps -a | grep 'sync-checks' | awk '{print $1}')
                  while docker ps | grep -q $container_id; do echo "checks running..."; sleep 5; done
                  exit_code=$(docker container inspect $container_id --format='{{.State.ExitCode}}')
                  if [ "$exit_code" != "0" ]; then
                    echo "Error: checks exited with code $exit_code"
                    exit 1
                  fi
            - name: Show logs - checks
              if: always()
              run: docker logs sync-checks-1
            - name: Show logs - sync-node
              if: always()
              run: |
                  sleep 20
                  docker logs sync-node-1
            - name: Show logs - api-http
              if: always()
              run: docker logs sync-api-http-1

    functional:
        name: "Functional - ${{matrix.name}}"
        if: true
        needs:
            - build
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-functional-${{matrix.name}}
        runs-on: ubuntu-latest

        timeout-minutes: 15

        strategy:
            matrix:
                node-version: [24.x]
                name: ["transaction-pool-api", "consensus", "resync"]

        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: test_db
                    POSTGRES_PASSWORD: password
                ports:
                    - 127.0.0.1:5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v7.0.1
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v6.0.10
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache/restore@v6.1.0
              with:
                  key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            - name: Cache lerna
              uses: actions/cache/restore@v6.1.0
              with:
                  key: lerna-${{ github.sha }}
                  path: ./.nx
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Test ${{ matrix.name }}
              run: cd tests/functional/${{ matrix.name }} && pnpm run test:full
