name: CI

on:
    pull_request:
        # push:
        #     branches:
        #         - "main"
        #         - "develop"
        # pull_request:
        #     types: [ready_for_review, synchronize, opened]

jobs:
    functional:
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-functional
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                name: ["consensus", "transaction-pool-api"]

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  run_install: false
                  version: latest
            - name: Get pnpm store directory
              id: pnpm-cache
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
              shell: bash
            - name: Cache pnpm modules
              uses: actions/cache@v3
              with:
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  restore-keys: ${{ runner.os }}-pnpm-
            - name: Cache lerna
              uses: actions/cache@v3
              with:
                  key: ${{ runner.os }}-lerna
                  path: ./.cache
                  restore-keys: ${{ runner.os }}-lerna-
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build

            - name: Test ${{ matrix.name }}
              run: cd tests/functional/${{ matrix.name }} && pnpm run test:full
