jobs:
    unit:
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-unit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - uses: pnpm/action-setup@v2
              with:
                  run_install: true
                  version: latest

            - name: Build
              run: pnpm run build
            - name: Test core
              run: cd packages/core && pnpm run test
            - name: Test blockchain
              run: cd packages/blockchain && pnpm run test
            - name: Test core-cli
              run: cd packages/core-cli && pnpm run test
            - name: Test core-crypto-address-base58
              run: cd packages/core-crypto-address-base58 && pnpm run test
            - name: Test core-crypto-address-bech32
              run: cd packages/core-crypto-address-bech32 && pnpm run test
            - name: Test core-crypto-address-bech32m
              run: cd packages/core-crypto-address-bech32m && pnpm run test
            - name: Test core-crypto-address-keccak256
              run: cd packages/core-crypto-address-keccak256 && pnpm run test
            - name: Test core-crypto-address-ss58
              run: cd packages/core-crypto-address-ss58 && pnpm run test
            - name: Test core-crypto-block
              run: cd packages/core-crypto-block && pnpm run test
            - name: Test crypto-hash-bcrypto
              run: cd packages/crypto-hash-bcrypto && pnpm run test
            - name: Test crypto-hash-noble
              run: cd packages/crypto-hash-noble && pnpm run test
            - name: Test crypto-hash-wasm
              run: cd packages/crypto-hash-wasm && pnpm run test
            - name: Test crypto-key-pair-bls12-381
              run: cd packages/crypto-key-pair-bls12-381 && pnpm run test
            - name: Test crypto-key-pair-ecdsa
              run: cd packages/crypto-key-pair-ecdsa && pnpm run test
            - name: Test crypto-key-pair-ed25519
              run: cd packages/crypto-key-pair-ed25519 && pnpm run test
            - name: Test crypto-key-pair-schnorr
              run: cd packages/crypto-key-pair-schnorr && pnpm run test
            - name: Test crypto-signature-bls12-381
              run: cd packages/crypto-signature-bls12-381 && pnpm run test
            - name: Test crypto-signature-ecdsa
              run: cd packages/crypto-signature-ecdsa && pnpm run test
            - name: Test crypto-signature-ed25519
              run: cd packages/crypto-signature-ed25519 && pnpm run test
            - name: Test crypto-signature-schnorr
              run: cd packages/crypto-signature-schnorr && pnpm run test
            - name: Test crypto-time
              run: cd packages/crypto-time && pnpm run test
            - name: Test crypto-transaction
              run: cd packages/crypto-transaction && pnpm run test
            - name: Test crypto-transaction-multi-payment
              run: cd packages/crypto-transaction-multi-payment && pnpm run test
            - name: Test crypto-transaction-multi-signature-registration
              run: cd packages/crypto-transaction-multi-signature-registration && pnpm run test
            - name: Test crypto-transaction-transfer
              run: cd packages/crypto-transaction-transfer && pnpm run test
            - name: Test crypto-transaction-validator-registration
              run: cd packages/crypto-transaction-validator-registration && pnpm run test
            - name: Test crypto-transaction-validator-resignation
              run: cd packages/crypto-transaction-validator-resignation && pnpm run test
            - name: Test crypto-transaction-vote
              run: cd packages/crypto-transaction-vote && pnpm run test
            - name: Test crypto-validation
              run: cd packages/crypto-validation && pnpm run test
            - name: Test crypto-wif
              run: cd packages/crypto-wif && pnpm run test
            - name: Test forger
              run: cd packages/forger && pnpm run test
            - name: Test kernel
              run: cd packages/kernel && pnpm run test
            - name: Test logger-pino
              run: cd packages/logger-pino && pnpm run test
            - name: Test p2p
              run: cd packages/p2p && pnpm run test
            - name: Test core-configuration-generator
              run: cd packages/core-configuration-generator && pnpm run test
            - name: Test core-state
              run: cd packages/core-state && pnpm run test
            - name: Test core-test-framework
              run: cd packages/core-test-framework && pnpm run test
            - name: Test core-transaction-pool
              run: cd packages/core-transaction-pool && pnpm run test
            - name: Test core-transactions
              run: cd packages/core-transactions && pnpm run test
            - name: Test core-validation
              run: cd packages/core-validation && pnpm run test
            - name: Test core-webhooks
              run: cd packages/core-webhooks && pnpm run test
            - name: Test utils
              run: cd packages/utils && pnpm run test
        strategy:
            matrix:
                node-version:
                    - 20.x
name: CI
on:
    pull_request:
        types:
            - ready_for_review
            - synchronize
            - opened
    push:
        branches:
            - main
            - develop
